init

diff --git a/deployment/node/sdu/sdu-continuum/post-install.sh.in b/deployment/node/sdu/sdu-continuum/post-install.sh.in
--- a/deployment/node/sdu/sdu-continuum/post-install.sh.in
+++ b/deployment/node/sdu/sdu-continuum/post-install.sh.in
@@ -1,1 +1,50 @@
-#!/bin/sh
+#!/bin/bash
+
+# master-file
+
+domaindir=/node/domains/seccaw
+index=http://continuum.apache.org/download.html
+
+echo "Parse index-1: $index"
+if ! index2=`grepurl -Em1 '[^"]+\.war' $index`; then
+    echo "  error"
+    exit 1
+fi
+
+echo "Parse index-2: $index2"
+if ! war_url=`grepurl -Em1 '[^"]+\.war' $index2`; then
+    echo "  error"
+    exit 1
+fi
+
+echo "Download $war_url..."
+if ! war_file=`wgetc $war_url`; then
+    echo "Failed to download $war_url"
+    exit 1
+fi
+
+echo "Config resources on seccaw"
+
+    seccaw-admin create-jdbc-resource \
+        --connectionpoolid seccadb_dev_pool \
+        users
+
+    seccaw-admin create-jdbc-resource \
+        --connectionpoolid seccadb_dev_pool \
+        continuum
+
+    #seccaw-admin create-javamail-resource \
+    #    --mailhost localhost \
+    #    --mailuser appserv \
+    #    --fromaddress mail_session@localhost \
+    #    mail/Session
+
+    # seccaw-admin create-jvm-options -Dappserver.home=$domaindir
+    # seccaw-admin create-jvm-options -Dappserver.base=$domaindir
+
+echo "Install war $war_file..."
+
+    seccaw-admin deploy \
+        --contextroot continuum \
+        --name continuum \
+        $war_file
