/node refactor.

diff --git a/deployment/node/sdu/sdu-vol-devuser/post-install.sh.in b/deployment/node/sdu/sdu-vol-devuser/post-install.sh.in
--- a/deployment/node/sdu/sdu-vol-devuser/post-install.sh.in
+++ b/deployment/node/sdu/sdu-vol-devuser/post-install.sh.in
@@ -1,2 +1,18 @@
 #!/bin/sh
 # master-file
+
+if ! mount-ebs devuser /mnt/devuser; then
+    echo "Failed to mount vol:devuser"
+    exit 1
+fi
+
+if [ ! -h /home ]; then
+    echo "Move anything under /home to vol:devuser"
+
+    cd /
+    cp -uRT /home /mnt/devuser
+    mv home home.bak
+    ln -snf /mnt/devuser home
+fi
+
+exit 0
