run&test to fix many errors.

diff --git a/deployment/node/sdu/sdu-vol-devdata/post-install.sh.in b/deployment/node/sdu/sdu-vol-devdata/post-install.sh.in
--- a/deployment/node/sdu/sdu-vol-devdata/post-install.sh.in
+++ b/deployment/node/sdu/sdu-vol-devdata/post-install.sh.in
@@ -11,16 +11,33 @@ else
     exit 1
 fi
 
+inst_name=`rsubstecho $inst_id`
+inst_name="${inst_name%[*}"
+
+mount_point=/mnt/devdata
+
 # 1, attach
-vol_devdata=`echo vol:devdata | substcat`
-att_dev=
-echo "Query the status of attachment $vol_devdata"
+vol_old=
+att_old=
+
+vol_cur=`substecho vol:devdata`
+att_cur=
+
+while read dev mp fs opts x y; do
+    if [ "$mp" = "$mount_point" ]; then
+        echo "Current $mount_point is attached to $inst_name: $dev"
+        att_old="$dev"
+        break
+    fi
+done </etc/fstab
+
+echo "Query the status of attachment $vol_cur"
 while read type vol inst dev status t0; do
     if [ "$type" != ATTACHMENT ]; then continue; fi
-    if [ "$vol" = $vol_devdata ]; then
+    if [ "$vol" = $vol_cur ]; then
         if [ "$inst" = $inst_id ]; then
             echo "Already attached to this instance: $dev"
-            att_dev="$dev"
+            att_cur="$dev"
             break
         elif [ "$status" = "attached" ]; then
             echo "Already attached to a different instance, try detach first"
@@ -28,37 +45,65 @@ while read type vol inst dev status t0; do
                 echo "Failed to detach, try with --force?"
                 exit 1
             else
-                att_dev=
+                att_cur=
             fi
         fi
         break
+    elif [ -n "$att_old" ]; then
+        if [ "$inst" = $inst_id ] && [ "$dev" = $att_old ]; then
+            echo "Detach the old volume $vol"
+            umount $att_old
+            if ! ec2-detach-volume $vol; then
+                echo "Failed to detach the old volume $vol, try with --force?"
+                exit 1
+            fi
+            while ec2-describe-volumes $vol | grep -q detaching; do
+                echo "Detaching..."
+            done
+            echo "Detached. "
+        fi
     fi
+
 done < <(NO_SUBST=1 ec2-describe-volumes)
 
-if [ -z "$att_dev" ]; then
-    if ! att_dev=`nextdev /dev/sd fghijklmnop`; then
-        echo "No more available /dev/sd? name"
-        exit 1
+if [ -z "$att_cur" ]; then
+
+    if [ -z "$att_old" ]; then
+        echo "Find next device name to attach"
+        if ! att_cur=`nextdev /dev/sd fghijklmnop`; then
+            echo "No more available /dev/sd? name"
+            exit 1
+        fi
+    else
+        att_cur=$att_old
     fi
 
-    echo "Attach vol:devdata to $att_dev" | substcat
-    if ! ec2-attach-volume vol:devdata -i $inst_id -d $att_dev; then
+    substecho "Attach vol:devdata to $att_cur"
+    if ! ec2-attach-volume vol:devdata -i $inst_id -d $att_cur; then
         echo "Failed to attach. "
         exit 1
     fi
+
+    while ec2-describe-volumes vol:devdata | grep -q attaching; do
+        echo "Attaching..."
+    done
+
+    echo "Resize2fs to fill any expansion"
+    resize2fs $att_cur
 fi
 
 # 2, mount
-mount_point=/mnt/devdata
 install -d -m 775 -o dev -g dev $mount_point
 
 if lineconf -e /etc/fstab $mount_point \
-        "$att_dev $mount_point ext3 defaults 0 0"; then
+        "$att_cur $mount_point ext3 defaults 0 0"; then
     echo "Updated entry in /etc/fstab. "
 
-    echo "Unmount $att_dev"
-    umount $att_dev
-
-    echo "Mount $att_dev on $mount_point"
-    mount $mount_point
+    echo "Unmount $att_cur"
+    umount $att_cur
 fi
+
+echo "Mount $att_cur on $mount_point"
+mount $mount_point
+
+exit 0
