initial

diff --git a/deployment/node/sdu/sdu-seccaw-jdbc-postgresql/post-install.sh.in b/deployment/node/sdu/sdu-seccaw-jdbc-postgresql/post-install.sh.in
--- a/deployment/node/sdu/sdu-seccaw-jdbc-postgresql/post-install.sh.in
+++ b/deployment/node/sdu/sdu-seccaw-jdbc-postgresql/post-install.sh.in
@@ -1,3 +1,38 @@
-#!/bin/sh
+#!/bin/bash
 
 # master-file
+
+shopt -s nullglob
+
+echo "Find latest jdbc jar"
+if ! jar_url=`grepurl -Em1 '[^"]+8.4-[0-9]*.jdbc4.jar' http://jdbc.postgresql.org/download.html`; then
+    echo "    Failed to search the latest jar. "
+    exit 1
+fi
+
+basename="${jar_url##*/}"
+libdir=/node/domains/seccaw/lib/databases
+put_file="$libdir/$basename"
+
+if [ -f "$put_file" ]; then
+    echo "    Already there: $put_file"
+else
+    echo "Download $jar_url"
+    if ! jar_file=`wgetc "$jar_url"`; then
+        echo "    Failed to download"
+        exit 1
+    fi
+
+    for ex in "$libdir"/postgresql-8.4-*; do
+        echo "Remove out-date jar: $ex"
+        rm -f "$ex"
+    done
+
+    echo "Put jar in $put_file"
+    sudo -uappserv cp "$jar_file" "$put_file"
+
+    echo "Restart seccaw server"
+    seccaw restart
+fi
+
+exit 0
